
FROM texlive/texlive:latest-doc
WORKDIR /workdir

RUN apt-get update \
  && apt-get install \
  libfontconfig \
  fonts-arphic-bkai00mp \
  fonts-arphic-bsmi00lp \
  fonts-arphic-gbsn00lp \
  fonts-arphic-gkai00mp \
  fonts-arphic-ukai \
  fonts-arphic-uming \
  fonts-noto-cjk
